#Application Configuration
server:
  port: 8999

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: firebase-service
        uri: lb://backoffice-firebase
        predicates:
        - Path=/backoffice/api/v1/messaging/**
        #filters:
        #- RewritePath=/backoffice/api/v1/messaging/*, /
      - id: security-service
        uri: lb://backoffice-security
        predicates:
        - Path=/backoffice/api/**,/api/auth/**,/api/test/**
      - id: device-service
        uri: lb://backoffice-device
        predicates:
        - Path=/backoffice/api/**
      - id: erp-service
        uri: lb://backoffice-erp
        predicates:
        - Path=/backoffice/api/**
      - id: console-service
        uri: lb://backoffice-console
        predicates:
        - Path=/backoffice/api/** 

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka
