#Application Configuration
server:
  port: 5002
  error:
    # include-message: always
    include-binding-errors: always

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/uphone-db?autoReconnect=true
    #url: jdbc:mariadb://uphone-db.cwhkndug0tzd.us-east-1.rds.amazonaws.com:3306/uphone-db?autoReconnect=true
    username: root
    #username: admin
    password: Uphone2021
    #password: Uphone2021

  jpa:
    show-sql: on
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
url:
  cliente: http://backoffice-shop/backoffice/api/v1/shop/cliente
  dispositivo: http://backoffice-catalog/backoffice/api/v1/catalog/dispositivo
  distribuidor: http://backoffice-shop/backoffice/api/v1/shop/distribuidor
  messaging: http://backoffice-firebase/backoffice/api/v1/messaging
  notificacion: http://backoffice-catalog/backoffice/api/v1/catalog/notificacion
  parametro: http://backoffice-catalog/backoffice/api/v1/catalog/parametro
