#Application Configuration
server:
  port: 8999

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
      routes:
      - id: firebase-service
        uri: lb://backoffice-firebase
        predicates:
        - Path=/backoffice/api/v1/messaging/**
        #filters:
        #- RewritePath=/backoffice/api/v1/messaging/*, /
      - id: device-service
        uri: lb://backoffice-device
        predicates:
        - Path=/backoffice/api/**
        #- Path=/backoffice/api/v1/device/**
        #filters:
        #- RewritePath=/backoffice/api/v1/device/*, /

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka
