#Application Configuration
server:
  port: 5000
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://uphone-db.cwhkndug0tzd.us-east-1.rds.amazonaws.com:3306/uphone-db?autoReconnect=true
    username: admin
    password: Uphone2021

  jpa:
    show-sql: on
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/