#Application Configuration
server:
  port: 8999

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: security-service
          uri: lb://backoffice-security
          predicates:
            - Path=/api/auth/**,/api/test/**
        - id: erp-service
          uri: lb://backoffice-erp
          predicates:
            - Path=/backoffice/api/v1/erp/**,/backoffice/api/v2/erp/**
          filters:
            - AuthFilter
        - id: device-service
          uri: lb://backoffice-device
          predicates:
            - Path=/backoffice/api/v1/device/**,/backoffice/api/v2/device/**
          filters:
            - AuthFilter
        - id: console-service
          uri: lb://backoffice-console
          predicates:
            - Path=/backoffice/api/v1/web/**,/backoffice/api/v2/web/**
          filters:
            - AuthFilter
        - id: firebase-service
          uri: lb://backoffice-firebase
          predicates:
            - Path=/backoffice/api/v1/messaging/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka
